* Coderkid-cli
    
   /Coderkid-cli/ is the command line interface for [[http://coderkid.com][coderkid.com]].
    
    I aim for this to be an easy way to learn all of the various topics I have on coderkid.com, and and easy interface for testing one's ability.
    
** Inspiration

   Much of this project was influenced by [[https://exercism.io][exercism.io]].

   Despite saying this, I had originally come up with this idea before ever being reminded of exercism's handy command-line tool, however, after I began writing this program, I looked to exercism's own implementation for pointers.
   I borrowed much of their program design.

   (Not including using Go, that was always going to happen).

** TODO TODO list
   - [ ] Build skeleton for basic commands
     - [ ] download (dl)
     - [ ] read (r)
     - [ ] test (t)
     - [ ] bug (b)
   - [ ] Write these tests
     - [ ] Command tests
       - [ ] download (dl)
       - [ ] read (r)
       - [ ] test (t)
       - [ ] bug (b)
     - [ ] Basic functionality
       - [ ] Welcome message
   - [ ] Write working commands
     - [ ] download (dl)
     - [ ] read (r)
     - [ ] test (t)
     - [ ] bug (b)
   - [ ] Add LICENSE

** TODO Future ideas
   - [ ] Have a login, with user history
   - [ ] User submittable almanacs and test
